REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE postgres FROM PUBLIC;

CREATE USER readonly;
GRANT CONNECT ON DATABASE postgres TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
GRANT USAGE ON SCHEMA PUBLIC TO readonly;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO readonly;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO readonly;

CREATE USER udefault;
GRANT CONNECT ON DATABASE postgres TO udefault;
GRANT USAGE ON SCHEMA PUBLIC TO udefault;
